// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package dbgen

import (
	"context"
)

const getActiveKeyMetadata = `-- name: GetActiveKeyMetadata :one
SELECT 
    api_key.project_id,
    projects.monthly_budget AS budget_limit
FROM api_key
JOIN projects ON api_key.project_id = projects.id
WHERE api_key.key_hash = $1 AND api_key.is_active = true
`

type GetActiveKeyMetadataRow struct {
	ProjectID   string
	BudgetLimit float64
}

func (q *Queries) GetActiveKeyMetadata(ctx context.Context, keyHash string) (GetActiveKeyMetadataRow, error) {
	row := q.db.QueryRow(ctx, getActiveKeyMetadata, keyHash)
	var i GetActiveKeyMetadataRow
	err := row.Scan(&i.ProjectID, &i.BudgetLimit)
	return i, err
}

const getProjectIDFromKeyHash = `-- name: GetProjectIDFromKeyHash :one
SELECT project_id FROM api_key
WHERE key_hash = $1
`

func (q *Queries) GetProjectIDFromKeyHash(ctx context.Context, keyHash string) (string, error) {
	row := q.db.QueryRow(ctx, getProjectIDFromKeyHash, keyHash)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}
