// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertSetting struct {
	ID                  string
	ProjectID           string
	SlackWebhookUrl     pgtype.Text
	EmailNotification   pgtype.Text
	TriggerThresholdPct int32
	IsTriggered         bool
}

type ApiKey struct {
	ID         string
	ProjectID  string
	KeyPrefix  string
	KeyHash    string
	IsActive   bool
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ModelRate struct {
	ID                     string
	Provider               string
	ModelName              string
	PromptTokenCostUsd     float64
	CompletionTokenCostUsd float64
	UpdatedAt              pgtype.Timestamptz
}

type Project struct {
	ID            string
	Name          string
	UserID        string
	MonthlyBudget float64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Spend         float64
}

type ProviderKey struct {
	ID           string
	ProjectID    string
	Provider     string
	EncryptedKey []byte
	Nonce        []byte
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UsageLog struct {
	ID               string             `json:"id"`
	ProjectID        string             `json:"project_id"`
	Model            string             `json:"model"`
	PromptTokens     int32              `json:"prompt_tokens"`
	CompletionTokens int32              `json:"completion_token"`
	CostUsd          float64            `json:"cost_usd"`
	StatusCode       int32              `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string
	GoogleID  string
	Email     string
	Name      string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
