// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertSetting struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	SlackWebhookUrl     pgtype.Text
	EmailNotification   pgtype.Text
	TriggerThresholdPct pgtype.Int4
	IsTriggered         pgtype.Bool
}

type ApiKey struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	KeyPrefix  string
	KeyHash    string
	IsActive   bool
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ModelRate struct {
	ID                     pgtype.UUID
	Provider               string
	ModelName              string
	PromptTokenCostUsd     pgtype.Numeric
	CompletionTokenCostUsd pgtype.Numeric
	UpdatedAt              pgtype.Timestamptz
}

type Project struct {
	ID            pgtype.UUID
	Name          string
	MonthlyBudget pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ProviderKey struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Provider     string
	EncryptedKey []byte
	Nonce        []byte
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UsageLog struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	CostUsd          pgtype.Numeric
	StatusCode       int32
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	GoogleID  string
	Email     string
	Name      string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
