// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects ( name, user_id, monthly_budget)
VALUES ($1, $2, $3)
RETURNING id, name, user_id, monthly_budget, created_at, updated_at
`

type CreateProjectParams struct {
	Name          string
	UserID        string
	MonthlyBudget float64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.UserID, arg.MonthlyBudget)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, name, user_id, monthly_budget, created_at, updated_at FROM projects
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.MonthlyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, user_id, monthly_budget, created_at, updated_at FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, name, user_id, monthly_budget, created_at, updated_at FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.MonthlyBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectBudget = `-- name: UpdateProjectBudget :one
UPDATE projects
SET monthly_budget = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, monthly_budget, created_at, updated_at
`

type UpdateProjectBudgetParams struct {
	ID            string
	MonthlyBudget float64
}

func (q *Queries) UpdateProjectBudget(ctx context.Context, arg UpdateProjectBudgetParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectBudget, arg.ID, arg.MonthlyBudget)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE projects
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, user_id, monthly_budget, created_at, updated_at
`

type UpdateProjectNameParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.MonthlyBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
