// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_key.sql

package dbgen

import (
	"context"
)

const getProviderKey = `-- name: GetProviderKey :one
SELECT encrypted_key, nonce 
FROM provider_keys
WHERE project_id = $1 AND provider = $2 AND is_active = true
`

type GetProviderKeyParams struct {
	ProjectID string
	Provider  string
}

type GetProviderKeyRow struct {
	EncryptedKey []byte
	Nonce        []byte
}

func (q *Queries) GetProviderKey(ctx context.Context, arg GetProviderKeyParams) (GetProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, getProviderKey, arg.ProjectID, arg.Provider)
	var i GetProviderKeyRow
	err := row.Scan(&i.EncryptedKey, &i.Nonce)
	return i, err
}
