// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_logs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUsageLog = `-- name: DeleteUsageLog :exec
DELETE FROM usage_logs
WHERE id = $1
`

func (q *Queries) DeleteUsageLog(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUsageLog, id)
	return err
}

const deleteUsageLogsByProject = `-- name: DeleteUsageLogsByProject :exec
DELETE FROM usage_logs
WHERE project_id = $1
`

func (q *Queries) DeleteUsageLogsByProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUsageLogsByProject, projectID)
	return err
}

const getTotalCostByProject = `-- name: GetTotalCostByProject :one
SELECT COALESCE(SUM(cost_usd), 0)::DECIMAL(10,6) AS total_cost
FROM usage_logs
WHERE project_id = $1
`

func (q *Queries) GetTotalCostByProject(ctx context.Context, projectID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalCostByProject, projectID)
	var total_cost float64
	err := row.Scan(&total_cost)
	return total_cost, err
}

const getTotalCostByProjectInRange = `-- name: GetTotalCostByProjectInRange :one
SELECT COALESCE(SUM(cost_usd), 0)::DECIMAL(10,6) AS total_cost
FROM usage_logs
WHERE project_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type GetTotalCostByProjectInRangeParams struct {
	ProjectID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) GetTotalCostByProjectInRange(ctx context.Context, arg GetTotalCostByProjectInRangeParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalCostByProjectInRange, arg.ProjectID, arg.CreatedAt, arg.CreatedAt_2)
	var total_cost float64
	err := row.Scan(&total_cost)
	return total_cost, err
}

const getUsageLogByID = `-- name: GetUsageLogByID :one
SELECT id, project_id, model, prompt_tokens, completion_tokens, cost_usd, status_code, created_at FROM usage_logs
WHERE id = $1
`

func (q *Queries) GetUsageLogByID(ctx context.Context, id string) (UsageLog, error) {
	row := q.db.QueryRow(ctx, getUsageLogByID, id)
	var i UsageLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageSummaryByModel = `-- name: GetUsageSummaryByModel :many
SELECT
    model,
    COUNT(*)                                         AS request_count,
    SUM(prompt_tokens)                               AS total_prompt_tokens,
    SUM(completion_tokens)                           AS total_completion_tokens,
    COALESCE(SUM(cost_usd), 0)::DECIMAL(10,6)       AS total_cost
FROM usage_logs
WHERE project_id = $1
GROUP BY model
ORDER BY total_cost DESC
`

type GetUsageSummaryByModelRow struct {
	Model                 string
	RequestCount          int64
	TotalPromptTokens     int64
	TotalCompletionTokens int64
	TotalCost             float64
}

func (q *Queries) GetUsageSummaryByModel(ctx context.Context, projectID pgtype.UUID) ([]GetUsageSummaryByModelRow, error) {
	rows, err := q.db.Query(ctx, getUsageSummaryByModel, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageSummaryByModelRow
	for rows.Next() {
		var i GetUsageSummaryByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUsageLog = `-- name: InsertUsageLog :one
INSERT INTO usage_logs (project_id, model, prompt_tokens, completion_tokens, cost_usd, status_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, model, prompt_tokens, completion_tokens, cost_usd, status_code, created_at
`

type InsertUsageLogParams struct {
	ProjectID        pgtype.UUID
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	CostUsd          float64
	StatusCode       int32
}

func (q *Queries) InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) (UsageLog, error) {
	row := q.db.QueryRow(ctx, insertUsageLog,
		arg.ProjectID,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostUsd,
		arg.StatusCode,
	)
	var i UsageLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CostUsd,
		&i.StatusCode,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageLogsByProject = `-- name: ListUsageLogsByProject :many
SELECT id, project_id, model, prompt_tokens, completion_tokens, cost_usd, status_code, created_at FROM usage_logs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageLogsByProjectParams struct {
	ProjectID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListUsageLogsByProject(ctx context.Context, arg ListUsageLogsByProjectParams) ([]UsageLog, error) {
	rows, err := q.db.Query(ctx, listUsageLogsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageLog
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLogsByProjectAndModel = `-- name: ListUsageLogsByProjectAndModel :many
SELECT id, project_id, model, prompt_tokens, completion_tokens, cost_usd, status_code, created_at FROM usage_logs
WHERE project_id = $1 AND model = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUsageLogsByProjectAndModelParams struct {
	ProjectID pgtype.UUID
	Model     string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListUsageLogsByProjectAndModel(ctx context.Context, arg ListUsageLogsByProjectAndModelParams) ([]UsageLog, error) {
	rows, err := q.db.Query(ctx, listUsageLogsByProjectAndModel,
		arg.ProjectID,
		arg.Model,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageLog
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLogsByProjectInRange = `-- name: ListUsageLogsByProjectInRange :many
SELECT id, project_id, model, prompt_tokens, completion_tokens, cost_usd, status_code, created_at FROM usage_logs
WHERE project_id = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
`

type ListUsageLogsByProjectInRangeParams struct {
	ProjectID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

func (q *Queries) ListUsageLogsByProjectInRange(ctx context.Context, arg ListUsageLogsByProjectInRangeParams) ([]UsageLog, error) {
	rows, err := q.db.Query(ctx, listUsageLogsByProjectInRange, arg.ProjectID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageLog
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostUsd,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
